

### GET ALL comments in every video
GET http://localhost:3001/api/comments


### POST a comment, need to be logged in
POST http://localhost:3001/api/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmxlc29jdGF2IiwiaWQiOiI2NGMyYTkxNjdiMzRmMmM3NWEwZDRmMGEiLCJpYXQiOjE2OTA0Nzg5MTV9.qlWfm8SxY7Zl3n86vbU6TnmQ0vCK0s9T_O9qvQgAt6E

{
    "comment": "This is a comment",
    "videoId": "64c2a8de7b34f2c75a0d4f08"
}


